name: Continuous Integration Workflow for Greenlight

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-audit:
    runs-on: ubuntu-latest

    env:
      ENTRYPOINT_DIR: ./cmd/api
      OUTPUT_BINARY: ./bin/greenlight

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.x'

    - name: Verify dependencies
      run: go mod verify

    - name: Build binary
      run: |
        echo "Building binary..."
        go build -o=${OUTPUT_BINARY} ${ENTRYPOINT_DIR}

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...